plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
packageExtensions:
  "debug@*":
    peerDependenciesMeta:
      "supports-color":
        optional: true