version: '3.8'

services:
  postgresql:
    image: postgres
    volumes:
      - db_datas:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA= /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432

volumes:
  db_datas:

