server:
  port: 8080

spring:
  profiles:
    active: default
    include:
      - db
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
       show_sql: true
      format_sql: true
