server:
  port: 8080

spring:
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb
      username: sa
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
       show_sql: true
      format_sql: true
